version: "3.9"

services:
  web:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "${HOST_PORT}:3000"
    env_file:
      - .env.${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
